using AutoMapper;
using CoperativeTelouet.Business.DTOs;
using CoperativeTelouet.Business.DTOs.Stockage;
using CoperativeTelouet.Domain.Entities.Stockage;

namespace CoperativeTelouet.Business.Mapping;

public class StockageProfile : Profile
{
    public StockageProfile()
    {
        // simple tables — convention maps everything by name
        CreateMap<ChambreFroide, ChambreFroideDto>();
        CreateMap<CreateChambreFroideDto, ChambreFroide>();
        CreateMap<UpdateChambreFroideDto, ChambreFroide>();

        CreateMap<VarietePomme, VarietePommeDto>();
        CreateMap<CreateVarietePommeDto, VarietePomme>();
        CreateMap<UpdateVarietePommeDto, VarietePomme>();

        CreateMap<StockBacsSociete, StockBacsSocieteDto>();
        CreateMap<UpdateStockBacsSocieteDto, StockBacsSociete>();

        // complex entity — read model is convention; server-computed fields are ignored on write
        CreateMap<BonEntreeStockage, BonEntreeStockageDto>();
        CreateMap<CreateBonEntreeStockageDto, BonEntreeStockage>()
            .ForMember(d => d.NumeroLot, o => o.Ignore())                 // generated by service
            .ForMember(d => d.PrixParBacParJourApplique, o => o.Ignore()) // snapshot by service
            .ForMember(d => d.BacsVidesAvant, o => o.Ignore())
            .ForMember(d => d.BacsVidesApres, o => o.Ignore())
            .ForMember(d => d.BacsPleinsAvant, o => o.Ignore())
            .ForMember(d => d.BacsPleinsApres, o => o.Ignore());
        CreateMap<UpdateBonEntreeStockageDto, BonEntreeStockage>();

        CreateMap<BonSortieStockage, BonSortieStockageDto>();
        CreateMap<CreateBonSortieStockageDto, BonSortieStockage>()
            .ForMember(d => d.BacsVidesAvant, o => o.Ignore())
            .ForMember(d => d.BacsVidesApres, o => o.Ignore())
            .ForMember(d => d.BacsPleinsAvant, o => o.Ignore())
            .ForMember(d => d.BacsPleinsApres, o => o.Ignore());
        CreateMap<UpdateBonSortieStockageDto, BonSortieStockage>();
    }
}
